# Generated by Django 4.1.1 on 2023-11-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_buyer'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='accounts.buyer')),
                ('items', models.ManyToManyField(blank=True, null=True, related_name='items', to='items.item')),
            ],
        ),
    ]
