# Generated by Django 4.1.1 on 2023-11-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_seller'),
        ('items', '0002_remove_item_name_item_description_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_items', to='shops.shop'),
        ),
    ]
